# Generated by Django 2.1.8 on 2020-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='click_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('isClicked', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
